name: CI

on:
  # workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  syntax_tests:
    name: Syntax tests
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: docker/setup-buildx-action@v2
      - name: Build and cache Syntest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./tests/docker/syntest.dockerfile
          # tags: syntest:latest
          scope: main
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run syntax tests
        run: tests/syntax.py
        env:
          DOCKER_BUILDKIT: 1

  highlight_regression_tests:
    name: Highlight regression tests
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Run highlight regression tests
        run: tests/highlight_regression.sh

  theme_regression_tests:
    name: Theme regression tests
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Run theme regression tests
        run: tests/theme_regression.sh
